clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      use-ssh: true
      remote-ssh: ssh://git@ssh.github.com:22/8ybing/woodpecker-ci.git

when:
  - event: push
    branch: main

steps:
  - name: build
    image: debian
    commands:
      - echo "This is the build step"
      - echo "binary-data-123" > executable
  - name: wood-ci
    image: golang:1.16
    commands:
      - echo "Testing ..."
      - ./executable